name: Build Test and Publish a Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  prep:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4

  build-ubuntu-jammy-aarch64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    needs: prep

    steps:
      - name: Build
        uses: jaldisdev/gel-pkg/integration/linux/build/ubuntu-jammy@master
        env:
          PACKAGE: edgedbpkg.edgedb:Gel
          SRC_REF: "${{ github.sha }}"
          PKG_REVISION: "<current-date>"
          PKG_PLATFORM: "ubuntu"
          PKG_PLATFORM_VERSION: "jammy"
          EXTRA_OPTIMIZATIONS: "true"
          BUILD_IS_RELEASE: "true"
          METAPKG_GIT_CACHE: disabled

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: builds-ubuntu-jammy-aarch64
          path: artifacts/ubuntu-jammy

  collect:
    needs: [build-ubuntu-jammy-aarch64]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - run: echo 'All build+tests passed, ready to publish now!'

  publish-ubuntu-jammy-aarch64:
    needs: [collect]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: builds-ubuntu-jammy-aarch64
          path: artifacts/ubuntu-jammy

      - name: Publish
        uses: jaldisdev/gel-pkg/integration/linux/upload/linux-x86_64@master
        env:
          PACKAGE_SERVER: sftp://uploader@package-upload.jaldis.com:8025/
          PKG_PLATFORM: "ubuntu"
          PKG_PLATFORM_VERSION: "jammy"
          PKG_PLATFORM_LIBC: ""
          PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
